Repository pulumi/pulumi-hugo, pull requests merged in 2021-05, with the labels that each got.

#182 redirect /support to https://support.pulumi.com/
  themes/default/content/support.md
  themes/default/content/support/_index.md
  themes/default/layouts/page/support.html
Labels: area/www

#189 remove apis text from apis and webhooks
  themes/default/content/blog/announcing-per-user-pricing-and-unlimited-stacks-for-teams/index.md
  themes/default/content/pricing/open-source-free-tier.md
  themes/default/layouts/page/pricing.html
Labels: area/www

#195 add get started page to website
  themes/default/assets/config/postcss.config.js
  themes/default/assets/js/copybutton.js
  themes/default/assets/sass/_buttons.scss
  themes/default/assets/sass/_copy-button.scss
  themes/default/assets/sass/_fonts.scss
  themes/default/assets/sass/_marketing.scss
  themes/default/assets/sass/_shape-backgrounds.scss
  themes/default/assets/sass/components/_install.scss
  themes/default/assets/sass/styles.scss
  themes/default/components/src/components.d.ts
  themes/default/components/src/components/convert/convert.tsx
  themes/default/components/src/components/install/install.e2e.ts
  themes/default/components/src/components/install/install.scss
  themes/default/components/src/components/install/install.spec.ts
  themes/default/components/src/components/install/install.tsx
  themes/default/content/get-started/_index.md
  themes/default/layouts/page/get-started.html
  themes/default/layouts/partials/docs/breadcrumb.html
  themes/default/layouts/partials/docs/toc.html
  themes/default/static/fonts/gilroy-bold.woff
  themes/default/static/fonts/gilroy-bold.woff2
Labels: area/www

#237 Upgrade Stencil.js
  themes/default/components/package.json
  themes/default/components/src/components.d.ts
  themes/default/components/src/components/banner/banner.e2e.ts
  themes/default/components/src/components/banner/banner.tsx
  themes/default/components/src/components/choosable/choosable.tsx
  themes/default/components/src/components/chooser/chooser.tsx
  themes/default/components/src/components/datetime/datetime.tsx
  themes/default/components/src/components/greenhouse-jobs-list/greenhouse-jobs-list.tsx
  themes/default/components/src/components/root/root.tsx
  themes/default/components/src/components/tooltip/tooltip.tsx
  themes/default/components/src/components/webinar-form-select/webinar-form-select.tsx
  themes/default/components/yarn.lock
Labels: kind/engineering

#235 change resource docs from 3-col to 2-col layout
  themes/default/assets/sass/_api-nodejs.scss
Labels: kind/enhancement

#241 move get started goals to beginning of guides
  themes/default/content/docs/get-started/aws/create-project.md
  themes/default/content/docs/get-started/azure/create-project.md
  themes/default/content/docs/get-started/gcp/create-project.md
  themes/default/content/docs/get-started/kubernetes/_index.md
  themes/default/content/docs/get-started/kubernetes/create-project.md
  themes/default/layouts/shortcodes/cloud-intro.html
Labels: kind/enhancement
