Repository pulumi/pulumi-hugo, pull requests merged in 2021-09, with the labels that each got.

#556 adjusting susan's title
  themes/default/data/team/team/susan-evans.toml
Labels: area/site

#551 improve messaging related to orgs and subscriptions
  themes/default/content/docs/intro/console/organizations.md
Labels: kind/enhancement

#640 Update the times of the Cloud Engineering Summit workshops
  themes/default/content/cloud-engineering-summit/_index.md
  themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md
  themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
  themes/default/content/resources/getting-started-with-automation-api/index.md
  themes/default/content/resources/getting-started-with-aws/index.md
  themes/default/content/resources/getting-started-with-azure-native/index.md
  themes/default/content/resources/getting-started-with-google-cloud-platform/index.md
Labels: blocked
