Repository pulumi/pulumi-hugo, pull requests merged in 2022-03, with the labels that each got.

#1110 Marking Cam as inactive 😢
  themes/default/data/team/team/cameron-stokes.toml
Labels: impact/no-changelog-required

#1134 Fix typo
  themes/default/content/_index.md
Labels: do-not-merge

#1139 Add track properties for pricing dialog
  themes/default/layouts/page/pricing.html
Labels: emergent
