Repository pulumi/pulumi-hugo, pull requests merged in 2022-11, with the labels that each got.

#2236 update stack transfer in docs
  themes/default/content/docs/intro/pulumi-service/projects-and-stacks.md
  themes/default/content/docs/support/faq.md
Labels: area/docs

#2264 uncomment blog tile, use updated blog link
  themes/default/layouts/page/reinvent.html
Labels: do-not-merge

#2282 Fix typo in ECS docs
  themes/default/content/docs/guides/crosswalk/aws/ecs.md
Labels: impact/no-changelog-required
