Repository pulumi/pulumi-hugo, pull requests merged in 2023-09, with the labels that each got.

#3229 Update Okta docs
  themes/default/content/docs/pulumi-cloud/access-management/saml/okta.md
  themes/default/content/docs/pulumi-cloud/access-management/scim/azuread.md
  themes/default/content/docs/pulumi-cloud/access-management/scim/okta.md
  themes/default/content/docs/pulumi-cloud/access-management/scim/onelogin.md
  themes/default/layouts/shortcodes/saml-warning.html
  themes/default/static/images/docs/guides/scim/azuread/advanced_options.png
  themes/default/static/images/docs/guides/scim/azuread/email_required.png
  themes/default/static/images/docs/guides/scim/azuread/mappings.png
  themes/default/static/images/docs/guides/scim/azuread/settings_scope.png
  themes/default/static/images/docs/guides/scim/azuread/userName.png
  themes/default/static/images/docs/guides/scim/console.png
  themes/default/static/images/docs/guides/scim/okta-application-selection-scim.png
  themes/default/static/images/docs/guides/scim/okta-pushgroups-menu-scim.png
  themes/default/static/images/docs/guides/scim/okta-scim-provisioning.png
  themes/default/static/images/docs/guides/scim/onelogin-application-rule.png
  themes/default/static/images/docs/reference/service/saml-okta/configure-saml-settings.png
  themes/default/static/images/docs/reference/service/saml-okta/create-okta-application.png
  themes/default/static/images/docs/reference/service/saml-okta/create-saml-integration.png
  themes/default/static/images/docs/reference/service/saml-okta/okta-xml-descriptor.png
  themes/default/static/images/docs/reference/service/saml-okta/pulumi-console-signin.png
  themes/default/static/images/docs/reference/service/saml-okta/pulumi-org-settings.png
  themes/default/static/images/docs/reference/service/saml-okta/user-assignments.png
  themes/default/static/images/docs/reference/service/saml-okta/view-setup-instructions.png
  themes/default/static/images/docs/reference/service/scim/azuread/advanced_options.png
  themes/default/static/images/docs/reference/service/scim/azuread/email_required.png
  themes/default/static/images/docs/reference/service/scim/azuread/mappings.png
  themes/default/static/images/docs/reference/service/scim/azuread/settings_scope.png
  themes/default/static/images/docs/reference/service/scim/azuread/userName.png
  themes/default/static/images/docs/reference/service/scim/okta/application-selection.png
  themes/default/static/images/docs/reference/service/scim/okta/attributes.png
  themes/default/static/images/docs/reference/service/scim/okta/general-enable-scim.png
  themes/default/static/images/docs/reference/service/scim/okta/profile-mapping.png
  themes/default/static/images/docs/reference/service/scim/okta/provisioning.png
  themes/default/static/images/docs/reference/service/scim/okta/push-groups-menu.png
  themes/default/static/images/docs/reference/service/scim/okta/usernames-set-on-create-only.png
  themes/default/static/images/docs/reference/service/scim/okta/view-teams.png
  themes/default/static/images/docs/reference/service/scim/onelogin/application-rule.png
Labels: size/S

#3340 Skip loading segment for specific user agents to filter bot traffic
  themes/default/layouts/partials/head.html
Labels: kind/enhancement

#3341 Update links in earlier Zephyr posts
  themes/default/content/blog/iac-recommended-practices-code-organization-and-stacks/index.md
  themes/default/content/blog/iac-recommended-practices-developer-stacks-git-branches/index.md
  themes/default/content/blog/iac-recommended-practices-rbac-and-security/index.md
  themes/default/content/blog/iac-recommended-practices-structuring-pulumi-projects/index.md
  themes/default/content/blog/iac-recommended-practices-using-stack-references/index.md
Labels: area/blog

#3350 Standardize language aliases
  themes/default/content/docs/languages-sdks/go/_index.md
  themes/default/content/docs/languages-sdks/java/_index.md
  themes/default/content/docs/languages-sdks/javascript/_index.md
  themes/default/content/docs/languages-sdks/python/_index.md
Labels: kind/enhancement, impact/usability, size/XS

#3372 Fix incorrect link to Katwalk repository
  themes/default/content/blog/deploy-ai-ml-vercel-app/index.md
Labels: area/blog, kind/bug, impact/usability

#3376 Update Puluminaries page
  themes/default/data/team/team/jowanza-joseph.toml
  themes/default/data/team/team/matt-stephenson.toml
  themes/default/data/team/team/tyler-mulligan.toml
  themes/default/static/images/team/jowanza-joseph.jpg
  themes/default/static/images/team/matt-stephenson.jpg
  themes/default/static/images/team/tyler-mulligan.jpg
Labels: kind/enhancement, size/S, impact/community, area/website

#2635 Blog post on benchmarking and improving Python program performance
  themes/default/content/blog/benchmarking-python-performance/index.md
  themes/default/content/blog/benchmarking-python-performance/meta.png
Labels: area/blog
