Repository pulumi/pulumi-hugo, pull requests merged in 2023-08, with the labels that each got.

#3196 Add admin tokens to access tokens perms table
  themes/default/content/docs/pulumi-cloud/access-management/access-tokens.md
Labels: area/docs, docs/content

#3260 Update _index.md - Fix Get Stack curl example
  themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md
Labels: size/S

#3273 Sarah/august workshops
  themes/default/content/resources/kubernetes-on-google-cloud/index.md
  themes/default/content/resources/kubernetes-platforms-on-google-cloud/index.md
  themes/default/static/images/resources/advanced-kubernetes-on-google-cloud-engin.png
Labels: do-not-merge

#3283 Add info for Microsoft Teams webhooks
  themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md
  themes/default/content/docs/pulumi-cloud/webhooks.md
Labels: size/S
