Repository pulumi/pulumi-hugo, pull requests merged in 2023-11, with the labels that each got.

#3572 Updates markdown to avoid right nav duplicate entries
  themes/default/content/docs/install/esc.md
Labels: area/docs, size/S

#3625 fixes nav dups in the main install page
  themes/default/content/docs/install/_index.md
Labels: area/docs

#3619 Add "What is configuration management" page
  themes/default/content/what-is/what-is-configuration-management.md
Labels: area/site, kind/enhancement, size/M, impact/seo

#3630 Add "What are Kubernetes Secrets" SEO Page
  themes/default/content/what-is/what-are-kubernetes-secrets.md
Labels: area/site, size/M, impact/seo, area/marketing

#3561 Update "What is IaC" page
  themes/default/content/what-is/what-is-infrastructure-as-code.md
Labels: kind/enhancement, area/website

#3641 Minor fixes to What is IaC page
  themes/default/content/what-is/what-is-infrastructure-as-code.md
Labels: kind/enhancement, size/S, impact/seo, area/website

#3647 Add ESC + Kubernetes blog post
  themes/default/content/blog/esc-kubernetes-cluster-and-app/index.md
  themes/default/content/blog/esc-kubernetes-cluster-and-app/meta.png
  themes/default/content/blog/esc-kubernetes-cluster-and-app/pulumi-esc-kubectl.gif
  themes/default/data/team/team/eron-wright.toml
  themes/default/static/images/team/eron-wright.jpg
Labels: area/blog

#3626 Add "What is Secrets Management" SEO page
  themes/default/content/what-is/what-is-secrets-management.md
Labels: kind/enhancement, size/M, impact/seo, area/website

#3680 Fix linting errors
  themes/default/content/what-is/what-is-aws-secrets-manager.md
  themes/default/content/what-is/what-is-azure-key-vault.md
Labels: emergent, kind/engineering, size/XS, area/website
