Repository pulumi/pulumi-hugo, pull requests merged in 2023-07, with the labels that each got.

#3192 Pulumi AI experimental Examples 2-8
  themes/default/content/resources/how-to-configure-multiple-apps-with-one-load-balancer-in-Kubernetes/index.md
  themes/default/content/resources/how-to-deploy-a-django-application-on-aws/index.md
  themes/default/content/resources/how-to-deploy-an-express-app-in-aws/index.md
  themes/default/content/resources/how-to-deploy-apache-kafka-in-aws/index.md
  themes/default/content/resources/how-to-deploy-nextjs-to-aws/index.md
  themes/default/content/resources/how-to-deploy-react-app-to-aws/index.md
  themes/default/content/resources/how-to-set-up-api-gateway-example/index.md
  themes/default/content/resources/how-to-setup-an-aws-api-gateway-to-listen-for-webhook-events/index.md
  themes/default/content/resources/how-to-use-snowflake-with-python-in-aws-lambda/index.md
  themes/default/layouts/resources/list.html
  themes/default/layouts/resources/rss.xml
  themes/default/theme/src/scss/_event-list.scss
Labels: area/docs

#3177 Fixes #3171 (docs)
  themes/default/content/docs/clouds/gcp/get-started/deploy-changes.md
Labels: area/docs, kind/enhancement, size/S, impact/usability

#3209 Fix EKS docs
  themes/default/content/docs/clouds/aws/guides/eks.md
Labels: size/S
