Repository pulumi/pulumi-hugo, pull requests merged in 2023-10, with the labels that each got.

#3431 Update documentation for github enterprise + pulumi #15212
  themes/default/content/docs/using-pulumi/continuous-delivery/github-app.md
  themes/default/static/images/docs/github-app/gh-enterprise-installation-app-name.png
  themes/default/static/images/docs/github-app/gh-enterprise-installation-dialog-organization.png
  themes/default/static/images/docs/github-app/gh-enterprise-installation-dialog-personal.png
  themes/default/static/images/docs/github-app/gh-enterprise-installation-dialog.png
  themes/default/static/images/docs/github-app/gh-enterprise-installation-selection.png
  themes/default/static/images/docs/github-app/gha-enterprise-server-install.png
  themes/default/static/images/docs/github-app/gha-install.png
Labels: impact/no-changelog-required

#3442 Add Anthony King to Puluminaries page
  themes/default/data/team/team/anthony-king.toml
  themes/default/static/images/team/anthony-king.jpg
Labels: area/site, kind/enhancement, size/S, impact/community

#3454 fixing nav for ESC
  themes/default/layouts/partials/header.html
Labels: kind/bug, area/marketing

#3508 Update blog with post detailing events of the outage on October 6
  themes/default/content/blog/post-mortem-2023-10-06/active-sessions-graph.png
  themes/default/content/blog/post-mortem-2023-10-06/index.md
  themes/default/content/blog/post-mortem-2023-10-06/meta.png
Labels: impact/no-changelog-required

#3450 Fix C# snippet
  themes/default/content/docs/languages-sdks/dotnet/_index.md
Labels: area/docs, kind/bug, resolution/fixed

#3375 Update azure.md
  themes/default/content/docs/pulumi-cloud/deployments/oidc/azure.md
Labels: area/docs, kind/enhancement

#3500 Updates aws cloudwatch example code in the guide
  themes/default/content/docs/clouds/aws/guides/cloudwatch.md
Labels: size/S

#3410 Remove -b content from getting-started guides
  themes/default/content/docs/clouds/aws/get-started/create-project-b.md
  themes/default/content/docs/clouds/aws/get-started/deploy-changes-b.md
  themes/default/content/docs/clouds/aws/get-started/deploy-stack-b.md
  themes/default/content/docs/clouds/aws/get-started/destroy-stack-b.md
  themes/default/content/docs/clouds/aws/get-started/modify-program-b.md
  themes/default/content/docs/clouds/aws/get-started/review-project-b.md
  themes/default/content/docs/clouds/azure/get-started/create-project-b.md
  themes/default/content/docs/clouds/azure/get-started/deploy-changes-b.md
  themes/default/content/docs/clouds/azure/get-started/deploy-stack-b.md
  themes/default/content/docs/clouds/azure/get-started/destroy-stack-b.md
  themes/default/content/docs/clouds/azure/get-started/modify-program-b.md
  themes/default/content/docs/clouds/azure/get-started/review-project-b.md
  themes/default/content/docs/clouds/gcp/get-started/create-project-b.md
  themes/default/content/docs/clouds/gcp/get-started/deploy-changes-b.md
  themes/default/content/docs/clouds/gcp/get-started/deploy-stack-b.md
  themes/default/content/docs/clouds/gcp/get-started/destroy-stack-b.md
  themes/default/content/docs/clouds/gcp/get-started/modify-program-b.md
  themes/default/content/docs/clouds/gcp/get-started/review-project-b.md
  themes/default/content/docs/clouds/kubernetes/get-started/create-project-b.md
  themes/default/content/docs/clouds/kubernetes/get-started/deploy-changes-b.md
  themes/default/content/docs/clouds/kubernetes/get-started/deploy-stack-b.md
  themes/default/content/docs/clouds/kubernetes/get-started/destroy-stack-b.md
  themes/default/content/docs/clouds/kubernetes/get-started/modify-program-b.md
  themes/default/content/docs/clouds/kubernetes/get-started/review-project-b.md
  themes/default/content/docs/get-started/b.md
Labels: needs-triage

#3564 Add Thomas Meckel as Puluminary
  themes/default/data/team/team/thomas-meckel.toml
  themes/default/static/images/team/thomas-meckel.jpg
Labels: kind/enhancement, size/S, area/website

#3565 Fix docs removing imports section
  themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md
Labels: area/docs

#3566 Fix typo: Referencing an(d) environment
  themes/default/content/docs/pulumi-cloud/esc/environments.md
Labels: area/docs
