Repository pulumi/pulumi-hugo, pull requests merged in 2023-12, with the labels that each got.

#3736 Fix python markdown display (for all clouds)
  themes/default/content/docs/clouds/aws/get-started/review-project.md
  themes/default/content/docs/clouds/azure/get-started/review-project.md
  themes/default/content/docs/clouds/gcp/get-started/review-project.md
Labels: kind/bug, size/XS

#3776 minor updates to aws pages
  themes/default/content/what-is/run-aws-cloudwatch-get-metric-data-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-dynamodb-list-tables-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-ec2-describe-instances-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-ec2-start-instances-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-ec2-stop-instances-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-iam-list-users-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-lambda-list-functions-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-s3-cp-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-s3-ls-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-s3-sync-with-dynamic-credentials.md
  themes/default/content/what-is/run-aws-sts-get-caller-identity-with-dynamic-credentials.md
  themes/default/layouts/what-is/single.html
Labels: area/marketing

#3711 Update platform engineering page
  themes/default/content/what-is/what-is-platform-engineering.md
Labels: size/M, area/website

#3782 Update gcp.md - modify subject claim documentation for clarity
  themes/default/content/docs/pulumi-cloud/oidc/gcp.md
Labels: kind/enhancement

#3787 Update deploy-changes.md
  themes/default/content/docs/clouds/aws/get-started/deploy-changes.md
Labels: kind/enhancement, size/XS, impact/first-48

#3793 Fix Go example for resource aliases
  themes/default/content/docs/concepts/options/aliases.md
Labels: area/docs, kind/bug, resolution/fixed
